<div class="alert alert-block alert-info">This Jupyter Notebook is part of the course <strong>"LLMs as Judges for Search" by OpenSource Connections.</strong>
    
Check out https://opensourceconnections.com/training/ for the full course and other classes.</div>

# Lab: Adding reasoning

In this lab we will add a user persona to our prompt. Please go ahead invent your own personas. We'll be adding some random prices to our data that you might want to reflect in your personas.

## Imports

In [2]:
import pandas as pd
import os
import json
from dotenv import load_dotenv
import os
import openai
from openai import OpenAI
from sklearn.metrics import cohen_kappa_score
import random

/opt/homebrew/lib/python3.10/site-packages/scipy/__init__.py:155: UserWarning: A NumPy version >=1.18.5 and <1.25.0 is required for this version of SciPy (detected version 1.25.2
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

In [5]:
load_dotenv(dotenv_path='../.env')

api_key = os.environ.get('OPENAI_API_KEY')

In [4]:
pd.set_option('display.max_colwidth', None)

## Product Data to Judge

Look at the following dataset. It contains search result data for the queries 'duct tape', 'iphone xr cool cases for teenage girls' and 'laptop'. This time we will only use products for the query ''iphone xr cool cases for teenage girls'.

In [6]:
df_products = pd.read_json('../data/esci-mini.json')

df_products

,query,product_id,esci_label,binary_label,label,product_title,product_description,product_bullet_point,product_brand,product_color,product_locale
0,duct tape,B00DJWTGAG,E,1,3,"3M 2979 Multi-Use Duct Tape, Silver, 1.88 in x 60 yd x 7 mil, 1 Pack, Temporary Repair, Patching, Tabbing, Capping Pipe, Marking, Labeling",None,"Commercial grade – Silver duct tape resists curling and tears off roll cleanly for light use in professional MRO/construction applications\nFlexible adhesive – Aggressive synthetic rubber adhesive sticks immediately to a wide variety of surfaces\nMulti-use applications– Great for patching, tabbing, light duty bundling, capping pipe, marking, labeling or temporary repair\nPriced for economy – This multipurpose contractor-grade tape is economically priced to best provide a quality temporary solution for light duties",3M,Silver,us
1,duct tape,B078M21NYH,E,1,3,"Craftzilla Rainbow Colored Duct Tape — 6 Bright Colors — 10 Yards x 2 Inch — No Residue, Tear by Hand & Waterproof — Great for Arts & Crafts, Color-Coding, and DIY Projects","This multi purpose rainbow set of duct tape colors and patterns is great for Students, Teachers, Parents, Artists, and Professionals. Use this colored duct tape for crafts and art projects that can be done in the classroom, studio, kitchen, home, or garage. The colorful duct tape rips nicely and cleanly so it can easily be used and applied to different surfaces. This fun duct tape bulk pack comes with 6 fun duct tape craft rolls - each roll measuring 10 yards of 2 inch duct tape. This includes 6 rolls in an assortment of bright neon duct tape colors (not fluorescent) including: Pink, Orange, Yellow, Green, Blue, Purple. This colorful tape set can be made into DIY arts and crafts projects such as the construction of forts, making duct tape wallets, keychains, origami, personalizing and decorating journals, notebooks, and luggages. This is also great for color-coding, labeling, and organizing use making it a fun addition to your DIY kits. Whenever you move or need storage organization, use these duct tape assorted colors to make labels for boxes and storage bins and put corresponding duct tape rainbow color tags to each room. Discover creative possibilities with these duct tape arts and crafts kits. Art is limitless so use this duct tape for boys, girls, adults, artists, and professionals!","Vivid Vibrance – Enjoy eye-catching brightness and a full rainbow of color options. Make labels, gifts, and statements—your multi purpose color duct tape pack from Craftzilla is both your palette and canvas.\nTearable and Easy to Clean – Assemble rainbow duct tape kits at home, in school, and on vacation. Your craft tapes are easy for tiny hands to tear for their craft and construction projects, and no hassle to peel off for easy cleanup with no residue.\nYou’re on a Roll – And you’ve got plenty left! With 60 total yards of wonderful hues and easy-tear workability, you can use your colored duct tape variety pack for project after project.\nCommunicate With Color – Apply your multi color duct tape anywhere you need to be heard without saying a word. Effortlessly label moving boxes, organize unruly TV cabling, and mark social-distancing spots.\nStick With Us – Count on Craftzilla for colored tape duct so fun, bright, and inspiring you won’t want to put it down. Your tape set is backed by our commitment to your colorful and crafty success.",Craftzilla,"Rainbow - Pink, Orange, Yellow, Green, Blue, Violet",us
2,duct tape,B0021L9MVO,I,0,0,"Duck HD Clear Heavy Duty Packing Tape, 1.88 Inch x 109 Yards, 6 Rolls (299016)",None,"Heavy duty for a strong and secure hold to keep your valuables safe while moving, shipping or in storage\nOffers wide temperature range performance for shipping and storage in hot or cold temperatures\nAdhesive bond strengthens over time for a long-lasting hold on boxes, perfect for storage\nCrystal clear to the core for a professional look on boxes or taping address labels\nMeets postal regulations for shipping tape",Duck,Clear,us
3,duct tape,B000CSS8UE,E,1,3,"Gorilla 6035180 Duct Tape, 1 Pack, Black",None,"Heavy duty and double thick, Gorilla Tape offers over-the top results; It's like duct tape on steroids\nGreat for indoor or outdoor use and made to stick to Rough, uneven, unforgiving surfaces like wood, stone, stucco, plaster, brick and more\nDouble-Thick adhesive; grips smooth, Rough and uneven surfaces\nTough, reinforced backing; the tight weave contributes to the heft, but Gorilla tape can still be ripped by hand\nRugged, weather-resistant shell; withstands moisture, UV rays and temperature extremes",Gorilla,Black,us
4,duct tape,B002O16SHC,E,1,3,"Duck Max Strength 240201 Duct Tape, 1-Pack 1.88 Inch x 45 Yard Silver",None,"High tensile strength for heavy duty hold for pros or DIYers wanting something stronger\nCo-extruded tape with waterproof backing for long-term repairs and all-weather performance making it ideal for bundling, sealing, waterproofing and hanging plastic sheeting\nAggressive rubber based adhesive for excellent holding power to masonry, wood, plastic and glass\nGreat stretch and conformability to hold tightly around corners, bends and curves\nHand tearable duct tape for quick application at home or on the construction site",Duck,Silver,us
5,duct tape,B0006VO7D4,I,0,0,"Duck 299002 Brand EZ Start Packaging Tape Clear, 60 Yards/Roll (Single)",None,"EZ Start eliminates any difficulty in starting the roll\nUnrolls smoothly, quietly and easily every time\nNo splitting or tearing\nNo splitting or tearing\nOffers a 2.6 mil thickness",Duck,Clear,us
6,duct tape,B0013LOU10,I,0,0,Electriduct D-2 Rubber Duct Cord Cover - 5 Feet Black Floor Cable Protector,"Strong enough to handle vehicular traffic, the D-2 rubber cord protector shields wires, power cord(s), and CAT5 (Category 5) cable(s) making this a must for any standard computer station set-up. The D-2 series rubber duct comes in three different colors (Black, Grey and Brown) and is available in 5-foot and 10-foot lengths that can be cut to fit and match any work area. This cord protector comes SLIT on the center channel for easy universal intallation for connected cables.","𝗘𝗩𝗘𝗥𝗬𝗧𝗛𝗜𝗡𝗚 𝗬𝗢𝗨 𝗡𝗘𝗘𝗗: The D-2 Rubber Duct is perfect for handling a standard computer station set-up: power cord(s), and ethernet/CAT6 cables, COAX cables, Phone lines, and more.\n𝗤𝗨𝗔𝗟𝗜𝗧𝗬: Made in the USA with High Quality Solid Extruded Rubber which makes it even easier to install. This product can be cut to any length and offers a skid-resistant grip to reduce slipping.\n𝗗𝗜𝗠𝗘𝗡𝗦𝗜𝗢𝗡𝗦: 1/2""H x 3/4""W Slit in the middle | Total Height: 3/4""; Total Width: 3-1/4""; Total Length: 60""\n𝗟𝗔𝗬 𝗙𝗟𝗔𝗧: This product is made from high quality rubber, and like all rubber, it will take shape in time, but for immediate results, place in any warmer area: outside in sunlight, warehouse, garage, etc. The cord cover will become very pliable.\n𝗣𝗥𝗘𝗠𝗜𝗨𝗠 𝗣𝗥𝗢𝗧𝗘𝗖𝗧𝗜𝗢𝗡: The D-2 Rubber Duct is designed to protect your loose floor cables from abrasions and prevents tripping. The generous channel size can accommodate a combination of power cords, ethernet/CAT6 cables, COAX cables, Phone lines, and more.",Electriduct,Black,us
7,duct tape,B00TE2XIR2,S,1,2,"ChromaLabel 1 Inch Clean Remove Color-Code Tape, 500 Inch Roll, Red","<p> Step up your organization and labeling projects with ChromaLabel's <b>One Inch Color-Coding Labeling Tape</b>! These colorful rolls of tape are suitable for countless applications -- whether you're a teacher making a custom chart, clerk filing important documents, company prioritizing tasks, or an aspiring artist creating a craft project with a burst of tasteful color.</p> <p>Writing on the tape with a <b>felt tip</b> marker allows you to further expand your usage options for pricing, custom identification, or initials on a special treat you wish to keep for yourself. Pressure Sensitive Adhesive of the multi-use tape ensures that it will stay just where you need it, and will have maximum adhesion to a clean, flat surface. However the tape can be removed without leaving residue on most surfaces. As with most self-adhesive products, the longer the tape is left to set, the more permanent the bond will be. The optimal temperature range for this product is 40 - 200˚F. The Five hundred inch long rolls are finished on a sturdy one inch core and cleanly shrink wrapped.</p> <p>Mix and match colors options to ensure you'll be able to lend your signature touch to many projects. Professional or DIY, at school or home, color-coding or just having fun -- take your project to the next level of style and function with 1"" Color-Code Labeling Tape from <b>ChromaLabel!</b></p>","Pressure Sensitive Adhesive keeps the 1 inch wide tape in place and removes cleanly from most surfaces without leaving residue\n500"" Total Length finished on 1"" Core and cleanly shrink wrapped\nMulti purpose tape is made of plasticized paper that is easy to write on with a felt tip marker\nCountless Uses in Retail, Office, Warehouse, Food Service, Classroom, and Medical\nAll ChromaLabel Products are proudly made in Kansas, the Heartland of the USA",ChromaLabel,Red,us
8,duct tape,B000GU437A,I,0,0,"Scotch Heavy Duty Shipping Packaging Tape, 1.88"" x 54.6 Yards, 3"" Core, Clear, Great for Packing, Shipping & Moving, 1 Roll, Dispensered (3850-RD)",None,"Guaranteed to Stay Sealed. *Proof of purchase required for reimbursement or replacement of tape. Contact: 1-800-3MHELPS\nProvides excellent holding power for heavy-duty packaging and shipping\nStrong seal on all box types, including harder-to-stick-to 100% recycled boxes. Seals seams with one strip so boxes stay closed.\nStrong, durable solvent-free hot melt adhesive seals and protects. Your heavy packages can bear the weight and stay sealed through it all.\nRelease coating makes unwind easy.",Scotch,Clear,us
9,duct tape,B01M9JRWW0,I,0,0,JVCC J90 Low Gloss Gaffer-Style Duct Tape: 4 in. (96mm Actual) x 75 ft. (Black),"<p><b>JVCC J90 Low Gloss Gaffer-Style Duct Tape</b> is a low gloss finish gaffer-style duct tape. It is a matte-finish polyethylene coated cloth tape with an adhesive that removes residue free from most surfaces (surface type & dwell time may affect removability). It is not as glossy as a traditional polyethylene-coated duct tape; however it would still be shinier than a vinyl-coated gaffers tape. It is also commonly referred to as AV cord tape. <b>JVCC J90 Gaffers Tape</b> is suitable for entertainment type applications (film, concerts, music, DJ's, conventions, trade shows, photography, etc.) where minimal visibility of tape is desired. Used for protecting and anchoring cable, wires and electrical cords; sealing of equipment cases and film canisters; and in stage set-ups for marking placement (i.e. ""spike"" tape). Also suitable as a book binding tape for seaming and reinforcement. <b>JVCC J90</b> conforms well to irregular surfaces, and will not twist or curl. Has excellent water, vapor and abrasion resistance. JVCC J90 is a lower adhesion AV cord tape so would not adhere well for very long to difficult to bond to surfaces like carpeting and would not hold vertically on a surface for very long. It's a lower cost alternative to standard gaffer tape.</p> NOTES: Sizes shipped will typically be the tape industry standard metric-cut sizes, i.e. 24mm for each 1 inch of nominal tape width ordered (rolls are approximately 5% narrower than the nominal size). This product's actual size is 96mm x 23m. This tape is typically cut to width from log rolls so most sizes ship on non-branded plain white cores. As with any adhesive tape product it is always the user's responsibility to determine that the product is suitable for their intended use; e.g. if you want to remove a product cleanly from a specific type of substrate please test on an inconspicuous area first. Warning: This product can expose you to chemicals including Carbon black (airborne, unbound particles o","JVCC J90 Low-Gloss Gaffer-Style Duct Tape is a matte-finish polyethylene coated cloth tape with a residue-free adhesive that's well-suited for a wide range of applications where low visibility is required. Unlike traditional polyethylene-coated duct tape, JVCC J90 tape offers a matte finish, but it's still slightly shinier than vinyl-coated gaffers tape. This tape is commonly referred to as AV cord tape. It won't leave behind any residue when removed.\nTape rolls are typically cut to standard tape industry metric-cut sizes - or approx 5% narrower than the nominal size (i.e. 24mm per 1-inch of nominal width ordered).\nAdhesive: natural rubber. Carrier/Backing: 76 mesh polyethylene coated cloth. Thickness: 11.8 mils (carrier, adhesive). Adhesion: 29 ounces per inch (to stainless steel test panel)\nTensile Strength: 36 pounds per inch (longitudinal). Service/Operating Temperature: -31°F to 176°F. Elongation: 12%. Core: 3 inch diameter neutral",J.V. Converting,Black,us
10,iphone xr cool cases for teenage girls,B07VN8CM9D,E,1,3,"iPhone XR Case,Red Rose Star iPhone XR Cases for Girls,Tempered Glass Back Cover Anti Scratch Reinforced Corners Soft TPU Bumper Shockproof Case for iPhone XR Starstruck Flower Color","<p><b>drophead is a company that specializes in selling mobile phone accessories, such as the pattern of toughened glass mobile phone case, which is carefully designed by us. The accessories are deeply rooted in creativity, quality and style.</b></p> <p>If you have suggestions for our products and services, you can inform us and leave feedback for our customer service.</p> <p><b>About the drophead iPhone XR Case<p><b> <ul> <li>iPhone XR Case is made of glass back cover and soft silicone TPU rubber around it.</li> </ul> <ul> <li>iPhone XR Case Protecting your device from scratches, dust, shock and fingerprint.</li> </ul> <ul> <li>High Quality Material to use for a longer time.Provided great protection for your iPhone XR.</li> </ul> <ul> <li>The hole position of iPhone XR Case is accurate and correct.</li> </ul> <ul> <li>Raised lips ensure extra protection of screen and back camera.Protecting your device from scratches, dust, shock and fingerprint</li> </ul> <ul> <li>Fits perfectly,full access to all ports, buttons, and features, Precise cutout ensures full access to all the functions and ports for your phone.</li> </ul> <ul> <li>Reinforcement and protection of the four corners of iPhone XR Case can prevent your mobile phone from breaking down and protect your mobile phone more durably.</li> </ul>","The company uses international advanced equipment and ink, clear patterns, bright colors, never fade. Your iPhone XR case is made of flexible thermoplastic polyurethane (TPU) and toughened glass.The personalized design of glass rear case makes your mobile phone more beautiful, scratch-resistant and wear-resistant,light and comfortable.\nPrecise cutout ensures full access to all the functions and ports for your iPhone XR; Sensitive button covers allow quick responsiveness.\nFULL-EDGE PROTECTION:Raised screen edge design and reinforced corner bumpers provide thorough security for your slim device at all sides and angles. The sleek raised-lip protects features of your iPhone XR – such as the screen, camera, and back surface – from scratches when lying flat.\nThe case of iPhone XR has four-corner reinforcement protection function, which can prevent the mobile phone from being strongly impacted when accidentally sliding, and more effectively protect the mobile phone.\n180 days 100% Money Back Guarantee:If you have any quality issues or any questions about your iPhone XR case, please feel free to contact us at the first time. We promise to resend you a new phone case.",ZHEGAILIAN,Red Rose Star,us
11,iphone xr cool cases for teenage girls,B07BGXBD1C,I,0,0,"A-Focus Compatible with iPhone 8 Plus Case for Girls, iPhone 7 Plus Case Pink, Colorful Pink Blue Red Abstract Cloud Frosted Shock Proof Slim Shell Case for iPhone 7 Plus 8 Plus 5.5 inch Matte Pink 4","1.Compatible with Apple iPhone 7 Plus (2016) & iPhone 8 Plus (2017).<br>2.IMD (In-Mould-Decoration) Technology: HD Color Printed under a Layer of PET, this print will never come off or fade.<br>3.Matte Surface, made of soft flexible TPU, full print, look like marble .<br>4.Full and easy access to the charging port, headphone jack, silent button, volume buttons and silent button, your device stays fully functional when it's in the case.<br>5.Package include: 1 x A-Focus Case for Apple iPhone 7 / 8 plus 5.5"", Accessory ONLY, Phone not included.","Compatible with Apple iPhone 7 Plus (2016) & iPhone 8 Plus (2017)\nIMD (In-Mould-Decoration) Technology: HD Color Printed under a Layer of PET, this print will never come off or fade\nMatte Surface, made of soft flexible TPU, full print, look like marble\nFull and easy access to the charging port, headphone jack, silent button, volume buttons and silent button, your device stays fully functional when it's in the case\nPackage include: 1 x A-Focus Case for Apple iPhone 7 plus / iphone 8 plus 5.5"", Accessory ONLY, Phone not included",A-Focus,red pink 4,us
12,iphone xr cool cases for teenage girls,B07RWYRVNN,E,1,3,"Artbling Case for iPhone XR 6.1"" Silicone 3D Cartoon Animal Cover,Kids Girls Boys Cool Cute Gost Cases,Kawaii Soft Gel Rubber Unique Fun Character Fashion Funny Protector for iPhoneXR (Green Alien)","Funermei is a professional seller on Amazon , we are always provide our customers with the best service and great products. If you have any comments about our products or service, just contact our customer service team directly, we will always be here for you. Thank you. <br> <br> <br> Compatible with Apple iPhone XR 6.1"" <br> <br> <br> -New cute and fashionable 3D designing, make your phone more creative and unique <br> <br> -Soft and comfortable touch, easy to grip and light weight; Easy to install and remove <br> <br> -The Durable Soft Silicone offers the maximum protection(scratch and corner protection) <br> <br>","▶[COMPATIBILITY]: Only fit for Apple iPhone XR 6.1"" smartphones all carriers(at&t,verizon,t-mobile,Sprint,Unlocked).\n▶[3D CARTOON DESIGN]: This cell phone protective case is in a very unique, cute, adorable cartoon style. People will compliments your case everywhere. It makes your phone stylish and fashion.\n▶[PRECISELY CUT]: New iPhone XR 6.1"" cell phone shockproof protective flexible case provide precise cutouts for speakers, microphones, cameras, charging Port, audio port and buttons for your Apple iPhoneXR, No Hassles. No Headaches.\n▶[SHOCK PROTECTION&PRETTY DESIGN]: Made of soft silicon to protect your phone from impact, drop, and shock.\n▶Does not come with built in screen protector! We recommend you use one pc or glass screen protector to provide more protection for your touch screen.",Funermei,"for iPhone XR 6.1""",us

Only use products for the query 'iphone xr cool cases for teenage girls'.

Add some random prices in the range between 20 and 60 USD.

In [9]:
random.seed(42)
df_cases = df_products[df_products['query'] == 'iphone xr cool cases for teenage girls'].copy()
df_cases['price'] = [random.randint(20, 60) for _ in range(df_cases.shape[0])]
df_cases

,query,product_id,esci_label,binary_label,label,product_title,product_description,product_bullet_point,product_brand,product_color,product_locale,price
10,iphone xr cool cases for teenage girls,B07VN8CM9D,E,1,3,"iPhone XR Case,Red Rose Star iPhone XR Cases for Girls,Tempered Glass Back Cover Anti Scratch Reinforced Corners Soft TPU Bumper Shockproof Case for iPhone XR Starstruck Flower Color","<p><b>drophead is a company that specializes in selling mobile phone accessories, such as the pattern of toughened glass mobile phone case, which is carefully designed by us. The accessories are deeply rooted in creativity, quality and style.</b></p> <p>If you have suggestions for our products and services, you can inform us and leave feedback for our customer service.</p> <p><b>About the drophead iPhone XR Case<p><b> <ul> <li>iPhone XR Case is made of glass back cover and soft silicone TPU rubber around it.</li> </ul> <ul> <li>iPhone XR Case Protecting your device from scratches, dust, shock and fingerprint.</li> </ul> <ul> <li>High Quality Material to use for a longer time.Provided great protection for your iPhone XR.</li> </ul> <ul> <li>The hole position of iPhone XR Case is accurate and correct.</li> </ul> <ul> <li>Raised lips ensure extra protection of screen and back camera.Protecting your device from scratches, dust, shock and fingerprint</li> </ul> <ul> <li>Fits perfectly,full access to all ports, buttons, and features, Precise cutout ensures full access to all the functions and ports for your phone.</li> </ul> <ul> <li>Reinforcement and protection of the four corners of iPhone XR Case can prevent your mobile phone from breaking down and protect your mobile phone more durably.</li> </ul>","The company uses international advanced equipment and ink, clear patterns, bright colors, never fade. Your iPhone XR case is made of flexible thermoplastic polyurethane (TPU) and toughened glass.The personalized design of glass rear case makes your mobile phone more beautiful, scratch-resistant and wear-resistant,light and comfortable.\nPrecise cutout ensures full access to all the functions and ports for your iPhone XR; Sensitive button covers allow quick responsiveness.\nFULL-EDGE PROTECTION:Raised screen edge design and reinforced corner bumpers provide thorough security for your slim device at all sides and angles. The sleek raised-lip protects features of your iPhone XR – such as the screen, camera, and back surface – from scratches when lying flat.\nThe case of iPhone XR has four-corner reinforcement protection function, which can prevent the mobile phone from being strongly impacted when accidentally sliding, and more effectively protect the mobile phone.\n180 days 100% Money Back Guarantee:If you have any quality issues or any questions about your iPhone XR case, please feel free to contact us at the first time. We promise to resend you a new phone case.",ZHEGAILIAN,Red Rose Star,us,60
11,iphone xr cool cases for teenage girls,B07BGXBD1C,I,0,0,"A-Focus Compatible with iPhone 8 Plus Case for Girls, iPhone 7 Plus Case Pink, Colorful Pink Blue Red Abstract Cloud Frosted Shock Proof Slim Shell Case for iPhone 7 Plus 8 Plus 5.5 inch Matte Pink 4","1.Compatible with Apple iPhone 7 Plus (2016) & iPhone 8 Plus (2017).<br>2.IMD (In-Mould-Decoration) Technology: HD Color Printed under a Layer of PET, this print will never come off or fade.<br>3.Matte Surface, made of soft flexible TPU, full print, look like marble .<br>4.Full and easy access to the charging port, headphone jack, silent button, volume buttons and silent button, your device stays fully functional when it's in the case.<br>5.Package include: 1 x A-Focus Case for Apple iPhone 7 / 8 plus 5.5"", Accessory ONLY, Phone not included.","Compatible with Apple iPhone 7 Plus (2016) & iPhone 8 Plus (2017)\nIMD (In-Mould-Decoration) Technology: HD Color Printed under a Layer of PET, this print will never come off or fade\nMatte Surface, made of soft flexible TPU, full print, look like marble\nFull and easy access to the charging port, headphone jack, silent button, volume buttons and silent button, your device stays fully functional when it's in the case\nPackage include: 1 x A-Focus Case for Apple iPhone 7 plus / iphone 8 plus 5.5"", Accessory ONLY, Phone not included",A-Focus,red pink 4,us,27
12,iphone xr cool cases for teenage girls,B07RWYRVNN,E,1,3,"Artbling Case for iPhone XR 6.1"" Silicone 3D Cartoon Animal Cover,Kids Girls Boys Cool Cute Gost Cases,Kawaii Soft Gel Rubber Unique Fun Character Fashion Funny Protector for iPhoneXR (Green Alien)","Funermei is a professional seller on Amazon , we are always provide our customers with the best service and great products. If you have any comments about our products or service, just contact our customer service team directly, we will always be here for you. Thank you. <br> <br> <br> Compatible with Apple iPhone XR 6.1"" <br> <br> <br> -New cute and fashionable 3D designing, make your phone more creative and unique <br> <br> -Soft and comfortable touch, easy to grip and light weight; Easy to install and remove <br> <br> -The Durable Soft Silicone offers the maximum protection(scratch and corner protection) <br> <br>","▶[COMPATIBILITY]: Only fit for Apple iPhone XR 6.1"" smartphones all carriers(at&t,verizon,t-mobile,Sprint,Unlocked).\n▶[3D CARTOON DESIGN]: This cell phone protective case is in a very unique, cute, adorable cartoon style. People will compliments your case everywhere. It makes your phone stylish and fashion.\n▶[PRECISELY CUT]: New iPhone XR 6.1"" cell phone shockproof protective flexible case provide precise cutouts for speakers, microphones, cameras, charging Port, audio port and buttons for your Apple iPhoneXR, No Hassles. No Headaches.\n▶[SHOCK PROTECTION&PRETTY DESIGN]: Made of soft silicon to protect your phone from impact, drop, and shock.\n▶Does not come with built in screen protector! We recommend you use one pc or glass screen protector to provide more protection for your touch screen.",Funermei,"for iPhone XR 6.1""",us,21
13,iphone xr cool cases for teenage girls,B07VP6845X,E,1,3,"iPhone Xs Case for Girls, YeLoveHaw Flexible Soft Slim Fit Full-Around Protective Cute Shell Phone Case Cover with Purple Floral and Gray Leaves Pattern for iPhone X/XS 5.8 Inch (Pink Flowers)","<b>IMD Series Cute Case for iPhone XS / X - Pink Flowers</b><br> <br> <b>Stylish Design</b><br> Nifty pink & purple flowers and dark grey leaves with grey background design elements makes you and your phone fashionable and chic, and perfectly match any occasions.<br> <br> <b>Unique Style</b><br> The pattern of this case is brand new and unique style, it makes you and your phone trendy and really different from others.<br> So don't hesitate to dress up your phone with it, and show your personality right now !<br> <br> <b>Full-body Protection</b><br> Flexible soft but really tough TPU material helps to shock absorbing, raised lip provides added protection for screen and camera.<br> <br> <b>Ultra-light & Durable</b><br> The shell phone case is slim fit and lightweight, it provides full around protection for your phone, and severs you the smooth touch feeling and anti-finger. <br> <br> <b>Perfect Fit</b><br> Precise cut and design, easy access to all ports, buttons, speakers, cameras and all features.<br> <br> <b>Convenient Use</b><br> This case can fit for your iPhone X / XS perfectly, easy to install and take off, pocket-friendly.<br> <br> <b>Unbeatable Price</b><br> The case is on new product promotions now, it serves you the best quality and design with attractive price, so if you love it, just buy it now.<br> <br><b>Package Includes :</b><br> 1x Case Cover for iPhone XS (2018) / iPhone X (2017)(5.8"" iPhone) (Case ONLY, Phone and other accessories not included.)<br> <b>1x Temporary tatoo sticker (Free gift)</b><br> <br> <b>**Kindly Remind**</b><br> The brand 'YeLoveHaw' and this product listing were originally created by <b>YeLoveHaw</b>. <br> Please pay attention to <b>choose the right seller, and notice the brand printed on the package, otherwise you may buy products that are not in conformity with the description</b>.","Unique flowers and leaves design pattern showcase your personality\nFull body protection, ultra-light but durable, raised lips provide added protection for screen and camera\nPrecise cut, easy access to all ports, buttons, speakers and cameras\nFlexible soft, fingerprint-resistant & smooth touch feeling, easy installation and removal\nCompatible with iPhone XS (2018) / iPhone X (2017)(5.8"" iPhone)",YeLoveHaw,Pink,us,37
14,iphone xr cool cases for teenage girls,B07Q3TW86X,I,0,0,"ooooops iPhone 8 Case,7 Case,SE Case for Girls, Green Leaves with White&Brown Flower Pattern Design, Slim Fit Clear Bumper Soft Full-Body Protective Cover Case for iPhone 7/8/SE 4.7''(Leaves&Flowers)","<b>Leaves & Floral Phone Case for iPhone SE / 8 / 7 :</b><br> <br> <b>Design Concept</b><br> Plant pattern - Kinds of leaves & flowers pattern design makes your phone much more attractive and stylish.<br> Frosting processing - Frosted touch feeling, make your phone not easy to fall off.<br> IMD technology - Makes the pattern vivid & never fade.<br> <br> <b>Product Features</b><br> - 360° shock-absorbing bump protection, cover all 4 sides even the buttons, raising lips help to protect camera & screen;<br> - Precise cutouts for all ports, buttons and camera;<br> - Flexible soft TPU material, slim-fit, lightweight & durable, easy to install and take off.<br> <br> <b>Package Content</b><br> 1 x phone case for iPhone 8 / 7 / SE <br> 1 x cell phone cleaning cloths (free gift)<br> Case & cleaning cloths only, phone or other accessories in the pictures are not included.<br> <br> <b>After-sale Services</b><br> Shipping, return & replacement services are <b>provided by Amazon</b>, you can buy this phonecase at ease.<br> <br> <br> <b>Trademark Notice</b><br> Trademark <b>[ ooooops ]</b> is owned by <b>seller ooooops</b>, we didn't authorize any third party to sell ooooops products.<br> Please make sure you choose the right seller, so as not to buy products that are inconsistent with the description.<br> <br>","[ Unique Design ] - Special lush plants pattern design, frosted touch feeling, fingerprint proof\n[ Full-body Protection ] - Cover the 4 sides, even the buttons; Bumper allover the 4 corners; Raised lips offer added protection for camera & screen\n[ Precise Cut ] - Precise cutouts for quick access, perfect fit your cellphone\n[ Easy Use ] - Flexible soft material, slim-fit, lightweight & durable, easy to install and take off\n[ Compatible Models ] - Compatible with iPhone SE (2020) / iPhone 8 (2017) / iPhone 7 (2016)",ooooops,"Green, White, Brown",us,35
15,iphone xr cool cases for teenage girls,B07H3P7D3R,E,1,3,"Ruky Case for iPhone XR Glitter Case, Gradient Quicksand Series TPU Bumper Cushion Reinforced Corners Protective Bling Liquid Girls Women Case for iPhone XR 6.1 inches, Gradient Pink","<br><b> Ruky Gradient Quicksand Series -- iPhone XR Glitter Liquid Phone Case for Women Girls</b><br> <br> 1.Combination of Glitter Liquid Design and hanging dying technology, Fashion and shiny appearance make your phone more attractive and fun to play with.<br> <br> 2.Slim design and perfect fit that adds minimum bulk to your phone. The Ruky shining case will give you a sense of comfortable and make your phone more fashionable at the same time.<br> <br>3.Precisely cutouts for speakers,charging ports,camera and buttons. Perfect dressing-up kit for your cell phone. <br> <br>4.3D flowing liquid case with bling sequins shiny glitters can attract your friends attention, the glitters and sequins could flow freely inside your case, funny to play. <br> <br>5.The material of this case is safe, non-toxic and eco-friendly, it pass the SGS Testing and it is not harmful to you. <br> <br><b> 6.You will get:</b><br> <br> 1 x iPhone XR Glitter Case","[Compatible with Apple iPhone XR (6.1"" )] This Glitter Liquid Case specially designed for iPhone XR (2018 release) with precise cutouts for all buttons and ports. And this iPhone XR glitter case supports wireless charging.\n[Shock Absorption TPU Bumper Cushion] Made of premium flexible TPU material, bendable and Anti-slip silicone bumper with [Shock Reduction] Reinforced Corner design give your phone strong protective and more comfortable grip.\n[Beauty&Luxury Bling Glitter Liquid Case] This glitter liquid design not only make your phone beauty but also more interesting to play, the bling love heart sequins could flow freely inside and change its color with floating up and down, give your loved one a big smile on her face.\n[Leak-Worry-Free Design] Soft TPU cover is flexible and bendable from cracking preventing leakage, and the liquid in this case is white mineral oil, which has passed SGS testing, non-toxic and eco-friendly, don't harm your body.\n[Ruky Customer Service] We provide Lifetime Friendly Customer Service. Please feel free to contact with us if any problem or suggestions.",Ruky,Gradient Pink,us,34
16,iphone xr cool cases for teenage girls,B07YKKPZJY,E,1,3,"Coralogo for iPhone XR TPU Case, 3D Cute Cartoon Funny Design Unique Character Protective Kawaii Fashion Fun Cool Stylish Cover Kits Skin Teens Kids Girls Boys Cases for iPhone XR 6.1"" (Sponge Patrick","<b>The brand is committed to providing quality products.</b><br> 1. This case is for iPhone XR. The special surface coating has anti-yellowing and long-lasting transparency.<br> 2. Cute and unique styles, Lovely and simple, that make your iPhone XR look stylish and different.<br> 3. Light and thin, doesn't add bulk to your phone. It is easy to switch between wired charging and wireless charging without removing the case. <br> 4. Shockproof, anti-drop, anti-scratch, anti-fingerprint, dustproof.<br> 5. If you have any questions, please let us know. We will answer your questions to bring you a good shopping experience.","【QUALITY MATERIALS】 This cute and chic cartoon Sponge Patrick iPhone XR case is made of a new TPU material, which is stylish and unique, the pattern is lively and interesting, and feels soft and comfortable. If you want to buy a new phone protective case, this is a good choice.\n【CLEAR IPHONE XR CASE】 This product is made of high-quality TPU material. It has smooth and soft handfeel and high transparency. It is not easy to yellow when used for a long time, and can maintain long-term transparency. The pattern is specially printed, so you don't have to worry about the pattern falling off after a long time of use.\n【SAFETY PERFORMANCE】 When you use this phone case, you don't have to worry about the phone being damaged. Because this case is anti-drop, shockproof and scratch-resistant. The camera hole edge is slightly higher than the phone camera, which can protect the phone camera well. Airbags are provided at the four corners of the case to prevent your phone from accidentally falling.\n【FITTING PHONE】 This case is perfect for your iPhone XR, easy to install and remove. The case is soft and does not scratch the edges of the phone when installed or removed. It does not interfere with the use of the phone keys and charging port. At the same time, it is very thin and only 2mm thick, which does not interfere with the use of wireless charging. (Make sure your phone has wireless charging), which is very convenient.\n【APPLICABLE PEOPLE】 This creative iPhone XR case is very different, if you want to give your family and friends a fun gift, you can choose this case, I believe they will love it very much.",Coralogo,"iPhone XR 6.1""",us,28
17,iphone xr cool cases for teenage girls,B07WGS2YHB,I,0,0,"YeLoveHaw iPhone SE 2020 Case, iPhone 8 Case, iPhone 7 Case for Girls, Flexible Soft Slim Fit, Floral and Purple & Gray Leaves Pattern Cute Phone Case for iPhone8 / iPhone7 / iPhoneSE (Pink Flowers)","<b>IMD Series Cute Case for iPhone SE 2020 / 8 / 7 - Pink Flowers</b><br> <br> <b>Stylish Design</b><br> Nifty pink & purple flowers and dark grey leaves with grey background design elements makes you and your phone fashionable and chic, and perfectly match any occasions.<br> <br> <b>Unique Style</b><br> The pattern of this case is brand new and unique style, it makes you and your phone trendy and really different from others.<br> So don't hesitate to dress up your phone with it, and show your personality right now !<br> <br> <b>Full-body Protection</b><br> Flexible soft but really tough TPU material helps to shock absorbing, raised lip provides added protection for screen and camera.<br> <br> <b>Ultra-light & Durable</b><br> The shell phone case is slim fit and lightweight, it provides full around protection for your phone, and severs you the smooth touch feeling and anti-finger. <br> <br> <b>Perfect Fit</b><br> Precise cut and design, easy access to all ports, buttons, speakers, cameras and all features.<br> <br> <b>Convenient Use</b><br> This case can fit for your iPhone SE / 8 / 7 perfectly, easy to install and take off, pocket-friendly.<br> <br> <b>Unbeatable Price</b><br> The case is on new product promotions now, it serves you the best quality and design with attractive price, so if you love it, just buy it now.<br> <br><b>Package Includes :</b><br> 1x Case Cover for iPhone 7 (2016) / iPhone 8 (2017) / iPhone SE (2020) (4.7 inch iPhone) (Case ONLY, Phone and other accessories not included.)<br> <b>1x Temporary tattoo sticker (Free gift)</b><br> <br> <b>**Kindly Remind**</b><br> The brand 'YeLoveHaw' and this product listing were originally created by <b>YeLoveHaw</b>. <br> Please pay attention to <b>choose the right seller, and notice the brand printed on the package, otherwise you may buy products that are not in conformity with the description</b>.","Unique flowers and leaves design pattern showcase your personality\nFull body protection, ultra-light but durable, raised lips provide added protection for screen and camera\nFlexible soft, fingerprint-resistant & smooth touch feeling, easy installation and removal\nPrecise cut, easy access to all ports, buttons, speakers and cameras. Support wireless charging\nCompatible with iPhone 7 (2016) / iPhone 8 (2017) / iPhone SE (2020) (4.7"" iPhone)",YeLoveHaw,Pink,us,26
18,iphone xr cool cases for teenage girls,B01FD9S34M,I,0,0,uCOLOR Pastel Gradient Case Compatible with iPhone 8 Compatible with iPhone 7/6S/6/ SE 2nd (2020) Abstract Cloud Protective case for iPhone 6S/6/8/7/SE 2nd Durable Soft TPU Case,"<b>Features</b><br>Shockproof case with screen protector.<br><br><br> -Full wrap-around design, the pattern goes all over the case including sides and back.<br> -Fits for all version of iPhone 8/7/6S/6<br> -Original, unique, stylish and professional designed artwork<br> <br> <br> -100% scratch proof and water proof<br> -Easy to snap in and access to all ports, control and sensors<br> -All our cases are made at our studio with healthy working conditions and not sweat shops <br> . <br> -Support wireless charge,does not affect the wireless charging function<br> -Raised bezels lift screen and camera off flat surfaces <br> PLEASE NOTE: Colors could vary due to different monitor settings, resolution and functions of your monitor. SO please be aware that when you receive your case, there may be very slight difference in color<br> Package: 1 x iPhone Case.(Not include the phone)<br>","Luxury gradient pink blue pastel cloud design iphone 6S/6/7/8 Case gift for girl and women\nDurable flexible Soft Case install and take off super stress free\nScreen and Camera Protection: 2mm higher than screen and 1mm higher than camera to offer the protection of your iPhone.\nSupport Wireless Charging Function\nPerfect fit for compatible iPhone 8 / 7 / 6S / 6 (4.7"" Size)",uCOLOR,Cloud,us,54

In [10]:
SYSTEM_PROMPT = """
You are an expert relevance judgment system. Your task is to assess the relevance of a given document to a specific user query.
The document has a product title and a price in USD. You will also be supplied with some information about the user.

Provide a relevance rating by assigning the label 'relevant' or 'not relevant', given the query, the user persona and the product.

In addition to the rating, provide a concise reasoning for your judgment.
First reason, then judge based on the reasoning.

Provide your relevance rating by assigning the label 'relevant' or 'not relevant' as property 'relevance' of an object in JSON format and the reasoning as property 'reasoning'.
"""

In [11]:
def make_user_prompt(query, doc_title, persona, price):
    return f"""
    
User Query: {query}

User Persona: {persona}

Document title:\n{doc_title}

Price: {price}

Based on the above, provide a relevance judgment."""

In [12]:
CLIENT = OpenAI(api_key=api_key)

def evaluate(query, doc_id, doc_title, persona, price, response_judgment_property='relevance', response_reasoning_property='reasoning', client=CLIENT, system_prompt=SYSTEM_PROMPT):
    
    try:
        # Send request to OpenAI API
        # Using generate_content and specifying the response_mime_type for JSON output
       
        response = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[
                {"role": "developer", "content": system_prompt},
                {
                    "role": "user",
                    "content": make_user_prompt(query, doc_title, persona, price),
                },
            ],
            response_format={"type": "json_object"},
            temperature=0.0
        )
        
        # Parse the JSON response
        json_output = response.choices[0].message.content
        judgment = json.loads(json_output)
        #print(judgment)
        
        return judgment[response_judgment_property], judgment[response_reasoning_property]
        
        

    except Exception as e:
        print(f"Error processing OpenAI judgment for Query: '{query[:30]}...', Doc ID: {doc_id}: {e}")
        raise e
        #return None

In [13]:
def evaluate_dataset(df, persona, response_judgment_property='relevance', response_reasoning_property='reasoning', client=CLIENT, system_prompt=SYSTEM_PROMPT):
    df = df.copy()
    df[['judgment','reasoning']] = df.apply(lambda row: evaluate(query=row['query'], doc_id=row['product_id'], doc_title=row['product_title'], 
                                                                 price=row['price'], persona=persona,
                                    response_judgment_property=response_judgment_property, 
                                    response_reasoning_property=response_reasoning_property, 
                                    client=client, system_prompt=system_prompt), axis=1, result_type="expand")
    df['binary_judgment'] = df['judgment'].apply(lambda j: 1 if j == 'relevant' else 0)

    return df

Define your persons below:

In [14]:
PERSONA = "A 50 year old person who always buys the best products and is shopping for their grand-daughter"

In [15]:
df_eval = evaluate_dataset(df_cases, persona=PERSONA)

In [16]:
df_eval[['query', 'product_title', 'price', 'judgment', 'reasoning']]

,query,product_title,price,judgment,reasoning
10,iphone xr cool cases for teenage girls,"iPhone XR Case,Red Rose Star iPhone XR Cases for Girls,Tempered Glass Back Cover Anti Scratch Reinforced Corners Soft TPU Bumper Shockproof Case for iPhone XR Starstruck Flower Color",60,relevant,"The document features an iPhone XR case specifically designed for girls, which aligns with the user query for 'cool cases for teenage girls.' The product title emphasizes its appeal to girls with the design and features, making it suitable for the user's granddaughter. The price indicates a premium product, which matches the user's persona of buying the best products."
11,iphone xr cool cases for teenage girls,"A-Focus Compatible with iPhone 8 Plus Case for Girls, iPhone 7 Plus Case Pink, Colorful Pink Blue Red Abstract Cloud Frosted Shock Proof Slim Shell Case for iPhone 7 Plus 8 Plus 5.5 inch Matte Pink 4",27,not relevant,"The document features a case for iPhone 7 Plus and 8 Plus, which does not match the user's query for iPhone XR cases. Additionally, while it is marketed towards girls, the specific model mismatch makes it irrelevant for the user's intent to find a cool case for their granddaughter's iPhone XR."
12,iphone xr cool cases for teenage girls,"Artbling Case for iPhone XR 6.1"" Silicone 3D Cartoon Animal Cover,Kids Girls Boys Cool Cute Gost Cases,Kawaii Soft Gel Rubber Unique Fun Character Fashion Funny Protector for iPhoneXR (Green Alien)",21,not relevant,"The document features a case for the iPhone XR that is described as a '3D Cartoon Animal Cover' targeted towards kids and includes terms like 'Kawaii' and 'Cute', which may not align with the preferences of a teenage girl. Additionally, the user persona is a 50-year-old person shopping for their granddaughter, who may be looking for more stylish or trendy options rather than something that is explicitly marketed towards younger children."
13,iphone xr cool cases for teenage girls,"iPhone Xs Case for Girls, YeLoveHaw Flexible Soft Slim Fit Full-Around Protective Cute Shell Phone Case Cover with Purple Floral and Gray Leaves Pattern for iPhone X/XS 5.8 Inch (Pink Flowers)",37,not relevant,"The document features a case for the iPhone Xs, not the iPhone XR as specified in the user query. Additionally, the user is a 50-year-old person shopping for their granddaughter, which suggests they may be looking for something specifically appealing to teenage girls. While the case is described as cute, it does not match the specific model requested, making it not relevant."
14,iphone xr cool cases for teenage girls,"ooooops iPhone 8 Case,7 Case,SE Case for Girls, Green Leaves with White&Brown Flower Pattern Design, Slim Fit Clear Bumper Soft Full-Body Protective Cover Case for iPhone 7/8/SE 4.7''(Leaves&Flowers)",35,not relevant,"The document features a case for iPhone 7/8/SE, which does not match the user's query for iPhone XR cases. Additionally, while the design may appeal to teenage girls, the user is specifically looking for cases for an iPhone XR, making this product irrelevant to their needs."
15,iphone xr cool cases for teenage girls,"Ruky Case for iPhone XR Glitter Case, Gradient Quicksand Series TPU Bumper Cushion Reinforced Corners Protective Bling Liquid Girls Women Case for iPhone XR 6.1 inches, Gradient Pink",34,relevant,"The document features a case specifically designed for the iPhone XR, which is the user's query. The product is described as a glitter case with a gradient pink design, appealing to teenage girls. Although the user is a 50-year-old shopping for their granddaughter, the product aligns well with the preferences of a teenage girl, making it a suitable choice."
16,iphone xr cool cases for teenage girls,"Coralogo for iPhone XR TPU Case, 3D Cute Cartoon Funny Design Unique Character Protective Kawaii Fashion Fun Cool Stylish Cover Kits Skin Teens Kids Girls Boys Cases for iPhone XR 6.1"" (Sponge Patrick",28,relevant,"The document features a case specifically designed for the iPhone XR, which is the product mentioned in the user query. Additionally, the case is described as having a 'cute cartoon' design and is targeted towards 'teens' and 'girls', aligning well with the interests of the user's granddaughter. The price is reasonable for a protective case, making it a suitable option for a grandparent looking to buy a gift."
17,iphone xr cool cases for teenage girls,"YeLoveHaw iPhone SE 2020 Case, iPhone 8 Case, iPhone 7 Case for Girls, Flexible Soft Slim Fit, Floral and Purple & Gray Leaves Pattern Cute Phone Case for iPhone8 / iPhone7 / iPhoneSE (Pink Flowers)",26,not relevant,"The document features a case for the iPhone SE 2020, iPhone 8, and iPhone 7, which are not compatible with the iPhone XR mentioned in the user query. Additionally, while the case is designed for girls, it does not specifically cater to the preferences of a teenage girl, as the user is shopping for their granddaughter. Therefore, it does not meet the user's needs."
18,iphone xr cool cases for teenage girls,uCOLOR Pastel Gradient Case Compatible with iPhone 8 Compatible with iPhone 7/6S/6/ SE 2nd (2020) Abstract Cloud Protective case for iPhone 6S/6/8/7/SE 2nd Durable Soft TPU Case,54,not relevant,"The document features a case that is compatible with older iPhone models (iPhone 6S/6/7/8/SE 2nd) rather than the iPhone XR specified in the user query. Additionally, while the case may appeal to teenage girls due to its pastel gradient design, the price of $54 may not align with the user's persona of seeking the best products for their granddaughter, especially if they are looking for options specifically for the iPhone XR."
19,iphone xr cool cases for teenage girls,"Logee TPU Spider Funny Cute Cartoon Clear Case for iPhone XR 6.1”,Fun Kawaii Animal Soft Protective Shockproof Cover,Ultra-Thin Chic Unique Creative Character Cases for Kids Teens Girls Boys(iPhoneXR)",25,not relevant,"The document features a case for the iPhone XR that is described as fun and cute, which aligns with the interests of teenage girls. However, the user persona is a 50-year-old person shopping for their granddaughter, who may prioritize quality and brand reputation over a 'fun' design. The title suggests it is aimed at a younger audience, and the user may be looking for something more sophisticated or high-end, making this product less relevant to their needs."